#!/usr/bin/env python3
"""从 Keil 工程生成 CMakeLists.txt（CubeMX 改动后重新运行即可同步）。

用法:
    python Script/gen_cmake.py
"""

import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(r"D:\GIT-SPACE\D00\APP\APP").resolve()
MDK = ROOT / "MDK-ARM"

GCC_STARTUP = "Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f407xx.s"
GCC_PORT = "Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c"
RVDS_PORT = "Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM4F/port.c"
RVDS_PORT_INC = "Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM4F"
GCC_PORT_INC = "Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F"

tree = ET.parse(MDK / "APP.uvprojx")
el = tree.getroot()

defines = []
for d in el.iter("Define"):
    if d.text and d.text.strip():
        defines += [x.strip() for x in d.text.split(",") if x.strip()]
defines = list(dict.fromkeys(defines))

incs = []
for inc in el.iter("IncludePath"):
    if inc.text and inc.text.strip():
        incs = [x.strip() for x in inc.text.split(";") if x.strip()]
        break

srcs, asms = [], []
for f in el.iter("File"):
    fp = f.findtext("FilePath")
    ft = f.findtext("FileType")
    if not fp:
        continue
    rel = (MDK / fp.replace("\\", "/")).resolve()
    try:
        rel = rel.relative_to(ROOT).as_posix()
    except ValueError:
        continue
    if ft == "2":
        if "startup_stm32f407xx.s" in rel:
            rel = GCC_STARTUP
        if rel not in asms:
            asms.append(rel)
    elif ft == "1":
        if rel == RVDS_PORT:
            rel = GCC_PORT
        if rel not in srcs:
            srcs.append(rel)

inc_paths = []
for inc in incs:
    rel = (MDK / inc.replace("\\", "/")).resolve()
    try:
        rel = rel.relative_to(ROOT).as_posix()
    except ValueError:
        continue
    if rel == RVDS_PORT_INC:
        rel = GCC_PORT_INC
    if rel not in inc_paths:
        inc_paths.append(rel)

def cmake_list(items, indent="    "):
    return "".join("%s%s\n" % (indent, i) for i in items)

content = """# ================================================================
# D00 APP - CMake fast incremental build (GCC toolchain / Ninja)
# Generated by Script/gen_cmake.py from MDK-ARM/APP.uvprojx.
# Do NOT hand-edit the file list; re-run the generator after CubeMX.
#
#   固件（交叉编译）：
#     cmake -S . -B build-cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ^
#           -DCMAKE_TOOLCHAIN_FILE=cmake/arm-none-eabi-toolchain.cmake
#     cmake --build build-cmake
#     artifacts: build-cmake/APP.bin  APP.elf  APP.map
#   主机单元测试（纯逻辑层，无需交叉工具链）：
#     cmake -S . -B build && cmake --build build && ctest --test-dir build
# ================================================================
cmake_minimum_required(VERSION 3.16)
project(D00_APP C ASM)

# 固件目标仅在交叉编译时构建；纯主机构建自动进入单元测试分支。
if(CMAKE_CROSSCOMPILING)

    set(CMAKE_SYSTEM_NAME Generic)
    set(CMAKE_SYSTEM_PROCESSOR arm)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

    # 工具链通过 -DCMAKE_TOOLCHAIN_FILE=cmake/arm-none-eabi-toolchain.cmake 注入

    add_compile_definitions(%(defines)s)

    set(CPU_FLAGS "-mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16")
    set(CMAKE_C_FLAGS "${CPU_FLAGS} -Os -ffunction-sections -fdata-sections -Wall -Wno-unknown-attributes -Wno-attributes -fno-common -fno-strict-aliasing" CACHE STRING "" FORCE)
    set(CMAKE_C_FLAGS_RELEASE "" CACHE STRING "" FORCE)
    set(CMAKE_ASM_FLAGS "${CPU_FLAGS} -x assembler-with-cpp" CACHE STRING "" FORCE)
    set(CMAKE_ASM_FLAGS_RELEASE "" CACHE STRING "" FORCE)
    set(CMAKE_EXE_LINKER_FLAGS "${CPU_FLAGS} -T${CMAKE_CURRENT_SOURCE_DIR}/cmake/APP.ld -Wl,--gc-sections -Wl,-Map=APP.map -Wl,--no-warn-rwx-segments --specs=nano.specs -u _printf_float" CACHE STRING "" FORCE)
    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "" CACHE STRING "" FORCE)

    include_directories(%(incs)s)

    set(APP_SOURCES
%(srcs)s
        Script/gcc_port/fault_handlers_gcc.c
        Script/gcc_port/syscalls_gcc.c)

    set(APP_ASM
%(asms)s)

    add_executable(APP.elf ${APP_SOURCES} ${APP_ASM})

    # LCD/FSMC 驱动对写时序敏感：-Os 的激进代码生成会改变 FSMC 写间隔，
    # 导致 ST7789 面板命令/窗口写入错乱（画面重叠/花屏，Keil 正常）。
    # 对驱动文件降级为 -O1，其余代码保持 -Os。
    set_source_files_properties(
        BSP/LCD/lcd.c
        BSP/LCD/lcd_ex.c
        BSP/bsp_lcd.c
        SystemServices/lcd_ui.c
        Application/lcd_app.c
        SystemServices/lcd_test.c
        SystemServices/touch_svc.c
        PROPERTIES COMPILE_FLAGS "-O1")

    add_custom_command(TARGET APP.elf POST_BUILD
        COMMAND ${CMAKE_OBJCOPY} -O binary APP.elf APP.bin
        COMMAND ${CMAKE_SIZE} APP.elf
        COMMENT "generate APP.bin"
    )
else()
    # ============================================================
    # 主机单元测试：纯逻辑层（协议 / CRC / 变量分片）
    # ============================================================
    add_executable(host_tests
        tests/test_protocol.c
        SystemServices/protocol.c
        SystemServices/crc16.c
        SystemServices/var_list.c
    )

    target_include_directories(host_tests PRIVATE
        SystemServices
        Config
        tests
    )

    if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options(host_tests PRIVATE -Wall -Wextra)
    endif()

    enable_testing()
    add_test(NAME host_tests COMMAND host_tests)
endif()
""" % {
    "defines": " ".join(defines),
    "incs": " ".join(inc_paths),
    "srcs": cmake_list(srcs),
    "asms": cmake_list(asms),
}

(ROOT / "CMakeLists.txt").write_text(content, encoding="utf-8")
print("CMakeLists.txt regenerated: %d C / %d ASM / %d include dirs"
      % (len(srcs), len(asms), len(inc_paths)))
